-- MySQL Script generated by MySQL Workbench
-- Fri Nov 19 00:24:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stackfulldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stackfulldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stackfulldb` DEFAULT CHARACTER SET utf8 ;
USE `stackfulldb` ;

-- -----------------------------------------------------
-- Table `stackfulldb`.`User Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stackfulldb`.`User Login` (
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Email`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stackfulldb`.`Business Name`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stackfulldb`.`Business Name` (
  `Name` VARCHAR(45) NOT NULL,
  `User Login_Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`, `User Login_Email`),
  INDEX `fk_Business Name_User Login1_idx` (`User Login_Email` ASC) VISIBLE,
  CONSTRAINT `fk_Business Name_User Login1`
    FOREIGN KEY (`User Login_Email`)
    REFERENCES `stackfulldb`.`User Login` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stackfulldb`.`Client List`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stackfulldb`.`Client List` (
  `Client Name` VARCHAR(45) NOT NULL,
  `User Login_Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Client Name`, `User Login_Email`),
  INDEX `fk_Client List_User Login1_idx` (`User Login_Email` ASC) VISIBLE,
  CONSTRAINT `fk_Client List_User Login1`
    FOREIGN KEY (`User Login_Email`)
    REFERENCES `stackfulldb`.`User Login` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stackfulldb`.`Client Contact Info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stackfulldb`.`Client Contact Info` (
  `Name` INT NOT NULL,
  `Phone` INT NULL,
  `Email` VARCHAR(45) NULL,
  `Address` VARCHAR(60) NULL,
  `Website` VARCHAR(45) NULL,
  `Client List_Client Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`, `Client List_Client Name`),
  INDEX `fk_Client Contact Info_Client List1_idx` (`Client List_Client Name` ASC) VISIBLE,
  CONSTRAINT `fk_Client Contact Info_Client List1`
    FOREIGN KEY (`Client List_Client Name`)
    REFERENCES `stackfulldb`.`Client List` (`Client Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stackfulldb`.`Projects List`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stackfulldb`.`Projects List` (
  `Project Name` VARCHAR(45) NOT NULL,
  `Client List_Client Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Project Name`, `Client List_Client Name`),
  INDEX `fk_Client Projects_Client List1_idx` (`Client List_Client Name` ASC) VISIBLE,
  CONSTRAINT `fk_Client Projects_Client List1`
    FOREIGN KEY (`Client List_Client Name`)
    REFERENCES `stackfulldb`.`Client List` (`Client Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stackfulldb`.`Invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stackfulldb`.`Invoice` (
  `Items` VARCHAR(45) NOT NULL,
  `Cost` INT NULL,
  `Projects List_Project Name` VARCHAR(45) NOT NULL,
  `Projects List_Client List_Client Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Items`, `Projects List_Project Name`, `Projects List_Client List_Client Name`),
  INDEX `fk_Invoice_Projects List1_idx` (`Projects List_Project Name` ASC, `Projects List_Client List_Client Name` ASC) VISIBLE,
  CONSTRAINT `fk_Invoice_Projects List1`
    FOREIGN KEY (`Projects List_Project Name` , `Projects List_Client List_Client Name`)
    REFERENCES `stackfulldb`.`Projects List` (`Project Name` , `Client List_Client Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stackfulldb`.`User Story`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stackfulldb`.`User Story` (
  `Story` VARCHAR(50000) NOT NULL,
  `Projects List_Project Name` VARCHAR(45) NOT NULL,
  `Projects List_Client List_Client Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Story`, `Projects List_Project Name`, `Projects List_Client List_Client Name`),
  INDEX `fk_User Story_Projects List1_idx` (`Projects List_Project Name` ASC, `Projects List_Client List_Client Name` ASC) VISIBLE,
  CONSTRAINT `fk_User Story_Projects List1`
    FOREIGN KEY (`Projects List_Project Name` , `Projects List_Client List_Client Name`)
    REFERENCES `stackfulldb`.`Projects List` (`Project Name` , `Client List_Client Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stackfulldb`.`Added Features`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stackfulldb`.`Added Features` (
  `Features List` VARCHAR(45) NOT NULL,
  `Projects List_Project Name` VARCHAR(45) NOT NULL,
  `Projects List_Client List_Client Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Features List`, `Projects List_Project Name`, `Projects List_Client List_Client Name`),
  INDEX `fk_Added Features_Projects List1_idx` (`Projects List_Project Name` ASC, `Projects List_Client List_Client Name` ASC) VISIBLE,
  CONSTRAINT `fk_Added Features_Projects List1`
    FOREIGN KEY (`Projects List_Project Name` , `Projects List_Client List_Client Name`)
    REFERENCES `stackfulldb`.`Projects List` (`Project Name` , `Client List_Client Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `stackfulldb` ;

-- -----------------------------------------------------
-- Placeholder table for view `stackfulldb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stackfulldb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `stackfulldb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stackfulldb`.`view1`;
USE `stackfulldb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
